apply plugin: 'java'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.testng:testng:7.12.0'
    implementation 'org.seleniumhq.selenium:selenium-java:4.44.0'
}

test {
    useTestNG()
}

compileJava.options.encoding = 'UTF-8'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}